// Generated by CoffeeScript 1.6.3
var MyCtrl, myApp;

MyCtrl = function($scope, $firebase) {
  var peopleRef;
  peopleRef = new Firebase("https://intense-fire-7647.firebaseio.com/people");
  $scope.people = $firebase(peopleRef);
  return $scope.addPerson = function() {
    $scope.people.$add({
      name: $scope.newName,
      age: $scope.newAge
    });
    return $scope.newPerson = '';
  };
};

myApp = angular.module('kahuna', ['firebase']);

myApp.controller('MyCtrl', ['$scope', '$firebase', MyCtrl]);
